[package]
name = "portfwd"
version = "0.1.0"
edition = "2021"
authors = ["忘忧北萱草 <wybxc@qq.com>"]

[dependencies]
clap = { version = "4.3", features = ["derive"] }

smol = "1.3"
num_cpus = "1.15"
easy-parallel = "3.3"

tracing = "0.1"
tracing-subscriber = "0.3"
